### ISSUE TITLE
Is that possible to install without composer?

### ISSUE THREAD

**Issue by csandreas1** [shevabam/recaptcha#5]
I can't install with composer way. Is that required?
If not how can i use it without composer?

**Comment by shevabam** [comment]
You absolutely can use it without Composer!
Just save the reCAPTCHA.php file located in src folder and paste it in your project.
Then, just include it and use the namespace : 

```php
include '/path/to/lib/reCAPTCHA.php';
use Phelium\Component\reCAPTCHA;
```
