### ISSUE TITLE
How to use reCAPTCHA getErrorCodes() 

### ISSUE THREAD

**Issue by levonter** [shevabam/recaptcha#6]
How to use reCAPTCHA getErrorCodes() 

I'd like to show error with : 

`foreach ($reCAPTCHA->getErrorCodes() as $code) {
			echo '<kbd>' , $code , '</kbd> ';
}`

there is nothing? is it possible to check?

**Comment by shevabam** [comment]
Thank you for your suggestion!
I added the function getErrorCodes() :

```php
if ($reCAPTCHA->isValid($_POST['g-recaptcha-response']))
{
	// do whatever you want, the captcha is valid
}
else
{
	// Show errors
	var_dump($reCAPTCHA->getErrorCodes());
}
```
